# frozen_string_literal: true

# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

TalkTable.create(input: 'あかいろ', message: 'りんご', tag: 'いろ')
TalkTable.create(input: 'あおいろ', message: 'そら', tag: 'いろ')
TalkTable.create(input: 'きいろ', message: 'きりん', tag: 'いろ')
TalkTable.create(input: 'みどりいろ', message: 'しんりん', tag: 'いろ')
TalkTable.create(input: 'ほげほげ', message: 'ぴよぴよ', tag: 'てきとう')
TalkTable.create(input: 'ふがふが', message: 'ふーばー', tag: 'てきとう')
TalkTable.create(input: 'いんぷっと00', message: 'めっせーじ00', tag: 'たぐ00')
TalkTable.create(input: 'いんぷっと01', message: 'めっせーじ01', tag: 'たぐ01')
TalkTable.create(input: 'いんぷっと02', message: 'めっせーじ02', tag: 'たぐ02')
TalkTable.create(input: 'いんぷっと03', message: 'めっせーじ03', tag: 'たぐ03')
TalkTable.create(input: 'いんぷっと04', message: 'めっせーじ04', tag: 'たぐ04')
TalkTable.create(input: 'いんぷっと05', message: 'めっせーじ05', tag: 'たぐ05')
TalkTable.create(input: 'いんぷっと06', message: 'めっせーじ06', tag: 'たぐ06')
TalkTable.create(input: 'いんぷっと07', message: 'めっせーじ07', tag: 'たぐ07')
TalkTable.create(input: 'いんぷっと08', message: 'めっせーじ08', tag: 'たぐ08')
TalkTable.create(input: 'いんぷっと09', message: 'めっせーじ09', tag: 'たぐ09')
TalkTable.create(input: 'いんぷっと10', message: 'めっせーじ10', tag: 'たぐ10')
TalkTable.create(input: 'いんぷっと11', message: 'めっせーじ11', tag: 'たぐ11')
TalkTable.create(input: 'いんぷっと12', message: 'めっせーじ12', tag: 'たぐ12')
TalkTable.create(input: 'いんぷっと13', message: 'めっせーじ13', tag: 'たぐ13')
TalkTable.create(input: 'いんぷっと14', message: 'めっせーじ14', tag: 'たぐ14')
TalkTable.create(input: 'いんぷっと15', message: 'めっせーじ15', tag: 'たぐ15')
TalkTable.create(input: 'いんぷっと16', message: 'めっせーじ16', tag: 'たぐ16')
TalkTable.create(input: 'いんぷっと17', message: 'めっせーじ17', tag: 'たぐ17')
TalkTable.create(input: 'いんぷっと18', message: 'めっせーじ18', tag: 'たぐ18')
TalkTable.create(input: 'いんぷっと19', message: 'めっせーじ19', tag: 'たぐ19')
TalkTable.create(input: 'いんぷっと20', message: 'めっせーじ20', tag: 'たぐ20')
TalkTable.create(input: 'いんぷっと21', message: 'めっせーじ21', tag: 'たぐ21')
TalkTable.create(input: 'いんぷっと22', message: 'めっせーじ22', tag: 'たぐ22')
TalkTable.create(input: 'いんぷっと23', message: 'めっせーじ23', tag: 'たぐ23')
TalkTable.create(input: 'いんぷっと24', message: 'めっせーじ24', tag: 'たぐ24')
TalkTable.create(input: 'いんぷっと25', message: 'めっせーじ25', tag: 'たぐ25')
TalkTable.create(input: 'いんぷっと26', message: 'めっせーじ26', tag: 'たぐ26')
TalkTable.create(input: 'いんぷっと27', message: 'めっせーじ27', tag: 'たぐ27')
TalkTable.create(input: 'いんぷっと28', message: 'めっせーじ28', tag: 'たぐ28')
TalkTable.create(input: 'いんぷっと29', message: 'めっせーじ29', tag: 'たぐ29')
TalkTable.create(input: 'いんぷっと30', message: 'めっせーじ30', tag: 'たぐ30')
TalkTable.create(input: 'いんぷっと31', message: 'めっせーじ31', tag: 'たぐ31')
